#!/usr/bin/env python3
"""Generate the SPARK units that mirror mjModel from the C X-macro tables.

Inputs : tools/fields.txt, tools/layout.txt   (written by the C dump tools)
Outputs: src/gen/mj-fields.ads, src/gen/mj-fixed.ads, src/gen/mj-models.ads, src/gen/mj-models.adb
Run    : python tools/gen.py           (from anywhere; paths are resolved from this file)
"""
from __future__ import annotations

import pathlib
import re
import sys
from dataclasses import dataclass

ROOT = pathlib.Path(__file__).resolve().parent.parent
GEN = ROOT / "src" / "gen"
TGEN = ROOT / "tests" / "gen"
FIELDS = ROOT / "tools" / "fields.txt"
LAYOUT = ROOT / "tools" / "layout.txt"

HEADER = "--  GENERATED by tools/gen.py from tools/fields.txt and tools/layout.txt. Do not edit.\n\n"

# ----------------------------------------------------------------------------- naming


def ada_name(c: str) -> str:
    """body_parentid -> Body_Parentid, M_rownnz -> M_Rownnz, mapM2D -> MapM2D."""
    return "_".join(p[:1].upper() + p[1:] for p in c.split("_"))


# C element type -> (Ada array type, Ada access type, element bytes, reader tag, zero literal)
ADA_TYPE = {
    "int":     ("Int_Array",     "Int_Array_Access",     4, "I32", "0"),
    "mjtNum":  ("Real_Array",    "Real_Array_Access",    8, "F64", "0.0"),
    "mjtByte": ("Byte_Array",    "Byte_Array_Access",    1, "U8",  "0"),
    "mjtBool": ("Byte_Array",    "Byte_Array_Access",    1, "U8",  "0"),
    "char":    ("Byte_Array",    "Byte_Array_Access",    1, "U8",  "0"),
    "float":   ("Float32_Array", "Float32_Array_Access", 4, "F32", "0.0"),
    "mjtSize": ("Int64_Array",   "Int64_Array_Access",   8, "I64", "0"),
}
FREE_PROC = {
    "Int_Array_Access": "Free_Int", "Real_Array_Access": "Free_Real", "Byte_Array_Access": "Free_Byte",
    "Float32_Array_Access": "Free_Float32", "Int64_Array_Access": "Free_Int64",
}

# Fields outside the named X-macro groups are assigned by name prefix (first match wins).
GROUP_OF_REST = [
    ("qpos", "QPOS"), ("bvh_", "BVH"), ("oct_", "BVH"), ("wrap_", "WRAP"), ("plugin", "PLUGIN"),
    ("numeric_", "NUMERIC"), ("text_", "TEXT"), ("tuple_", "TUPLE"), ("key_", "KEY"),
    ("name_", "NAME"), ("names", "NAME"), ("paths", "NAME"),
    ("B_", "SPARSE"), ("M_", "SPARSE"), ("D_", "SPARSE"), ("map", "SPARSE"),
]
GROUP_ORDER = ["BODY", "JOINT", "DOF", "TREE", "GEOM", "SITE", "CAMERA", "LIGHT", "FLEX", "MESH",
               "SKIN", "HFIELD", "TEXTURE", "MATERIAL", "PAIR", "EXCLUDE", "EQUALITY", "TENDON",
               "ACTUATOR", "SENSOR", "QPOS", "BVH", "WRAP", "PLUGIN", "NUMERIC", "TEXT", "TUPLE",
               "KEY", "NAME", "SPARSE"]
GROUP_FIELD = {"BODY": "Bodies", "JOINT": "Joints", "DOF": "Dofs", "TREE": "Trees", "GEOM": "Geoms",
               "SITE": "Sites", "CAMERA": "Cameras", "LIGHT": "Lights", "FLEX": "Flexes",
               "MESH": "Meshes", "SKIN": "Skins", "HFIELD": "Hfields", "TEXTURE": "Textures",
               "MATERIAL": "Materials", "PAIR": "Pairs", "EXCLUDE": "Excludes",
               "EQUALITY": "Equalities", "TENDON": "Tendons", "ACTUATOR": "Actuators",
               "SENSOR": "Sensors", "QPOS": "Qpos", "BVH": "Bvh", "WRAP": "Wraps", "PLUGIN": "Plugins",
               "NUMERIC": "Numerics", "TEXT": "Texts", "TUPLE": "Tuples", "KEY": "Keys",
               "NAME": "Names", "SPARSE": "Sparse"}


def group_type(g: str) -> str:          # BODY -> Body_Arrays (not _Group: geom_group etc. are Field_Id literals)
    return g.capitalize() + "_Arrays"


# Longest chain of calls that update one component each of the same record, in the
# generated free procedures and group readers. gnatwhy3's memory grows far faster than
# linearly with that chain length (83 calls: killed above 5 GB; 11 calls of 8: 7 s).
CHUNK = 8


def chunks(fs: list) -> list:
    return [fs[i:i + CHUNK] for i in range(0, len(fs), CHUNK)]


def group_prefix(g: str) -> str:        # BODY -> Body   (used for Body_Layout_OK etc.)
    return g.capitalize()


# ----------------------------------------------------------------------------- tables


@dataclass
class Field:
    ctype: str
    name: str
    nr: str
    nc: str
    group: str

    @property
    def ada(self) -> str:
        return ada_name(self.name)

    @property
    def atype(self) -> str:
        return ADA_TYPE[self.ctype][0]

    @property
    def acc(self) -> str:
        return ADA_TYPE[self.ctype][1]

    @property
    def nbytes(self) -> int:
        return ADA_TYPE[self.ctype][2]

    @property
    def reader(self) -> str:
        return ADA_TYPE[self.ctype][3]

    @property
    def zero(self) -> str:
        return ADA_TYPE[self.ctype][4]


@dataclass
class Tables:
    meta: dict
    sizes: list          # C size names in MJMODEL_SIZES order
    fields: list         # Field, in MJMODEL_POINTERS order
    opt: list            # (is_vec, ctype, name, n)
    stat: list           # (is_vec, name, n)
    vis: list            # (is_vec, sub, ctype, name, n)
    sizeof: dict         # struct -> bytes
    offset: dict         # (struct, member) -> bytes


def load_tables() -> Tables:
    meta, sizes, ptrs, grouped, opt, stat, vis = {}, [], [], {}, [], [], []
    for line in FIELDS.read_text().splitlines():
        p = line.split()
        if not p:
            continue
        k = p[0]
        if k == "META":
            meta[p[1]] = int(p[2])
        elif k == "SIZE":
            sizes.append(p[1])
        elif k == "PTR":
            if p[1] == "ALL":
                ptrs.append(p[2:6])
            else:
                grouped[p[3]] = p[1]
        elif k in ("OPT", "OPTVEC"):
            opt.append((k == "OPTVEC", p[1], p[2], int(p[3])))
        elif k in ("STAT", "STATVEC"):
            stat.append((k == "STATVEC", p[1], int(p[2])))
        elif k in ("VIS", "VISVEC"):
            vis.append((k == "VISVEC", p[1], p[2], p[3], int(p[4])))
        else:
            sys.exit(f"fields.txt: unknown line kind {k!r}")
    if meta.get("nsize") != len(sizes) or len(sizes) != 98:
        sys.exit(f"expected 98 sizes, got {len(sizes)} (META nsize {meta.get('nsize')})")
    if meta.get("version") != 3_014_000:
        sys.exit(f"expected MuJoCo 3.14.0, got version {meta.get('version')}")
    if meta.get("nptr") != len(ptrs) or len(ptrs) != 487:
        sys.exit(f"expected 487 pointer fields, got {len(ptrs)} (META nptr {meta.get('nptr')})")
    fields = []
    for ctype, name, nr, nc in ptrs:
        g = grouped.get(name)
        if g is None:
            g = next((grp for pre, grp in GROUP_OF_REST if name.startswith(pre)), None)
            if g is None:
                sys.exit(f"no group rule for ungrouped field {name}")
        fields.append(Field(ctype, name, nr, nc, g))
    sizeof, offset = {}, {}
    for line in LAYOUT.read_text().splitlines():
        p = line.split()
        if not p:
            continue
        if p[0] == "SIZEOF":
            sizeof[p[1]] = int(p[2])
        elif p[0] == "OFFSET":
            offset[(p[1], p[2])] = int(p[3])
    return Tables(meta, sizes, fields, opt, stat, vis, sizeof, offset)


# ----------------------------------------------------------------------------- expressions

SIZE_LONG = {"narena", "nbuffer"}            # informational int64 fields
SIZE_OPT = {"nemax", "njmax", "nconmax"}     # may be -1


def nc_long(nc: str, meta: dict, s: str = "S") -> str:
    """Column count as a Int64 expression over the Sizes record `s`."""
    m = re.fullmatch(r"MJ_M\((\w+)\)(?:\*(\d+))?", nc)
    if m:
        e = f"Int64 ({s}.{ada_name(m.group(1))})"
        return f"{e} * {m.group(2)}" if m.group(2) else e
    if nc.isdigit():
        return nc
    if nc in meta:
        return str(meta[nc])
    sys.exit(f"unknown column expression {nc!r}")


def count_long(f: Field, meta: dict, s: str = "S") -> str:
    """Element count of field f as a Int64 expression."""
    return f"Int64 ({s}.{ada_name(f.nr)}) * ({nc_long(f.nc, meta, s)})"


# ----------------------------------------------------------------------------- emitters


def write(path: pathlib.Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(HEADER + text, newline="\n")


def emit_fields(t: Tables) -> None:
    lits = ["None", "Header", "Size_Table", "Option_Block", "Visual_Block", "Statistic_Block",
            "Flag_Block"] + [f.ada for f in t.fields] + ["Capacity_Block"]
    body = ",\n      ".join(lits)
    write(GEN / "mj-fields.ads", f"""with MJ.Types; use MJ.Types;

package MJ.Fields with SPARK_Mode is

   --  Every array of mjModel plus the fixed blocks of the .mjb file, used to
   --  name the field a load or validation failure refers to.
   type Field_Id is
     ({body});

   type Load_Result is record
      Status : Load_Status := OK;
      Field  : Field_Id    := None;
      Index  : Integer     := -1;   --  element index, or -1 when not applicable
   end record;

   OK_Result : constant Load_Result := (Status => OK, Field => None, Index => -1);

end MJ.Fields;
""")


FIXED_SCALAR = {"mjtNum": ("Real", "0.0"), "int": ("Integer", "0"), "float": ("Float", "0.0")}
FIXED_VECTOR = {"mjtNum": "Real_Array", "float": "Float32_Array", "int": "Int_Array"}


def fixed_component(is_vec: bool, ctype: str, name: str, n: int) -> str:
    if is_vec:
        return f"      {ada_name(name):<16} : {FIXED_VECTOR[ctype]} (0 .. {n - 1}) := [others => {FIXED_SCALAR[ctype][1]}];"
    typ, zero = FIXED_SCALAR[ctype]
    return f"      {ada_name(name):<16} : {typ} := {zero};"


def emit_fixed(t: Tables) -> None:
    out = ["with MJ.Types; use MJ.Types;\n\npackage MJ.Fixed with SPARK_Mode is\n"]
    # mjOption
    out.append("   type Option is record")
    for is_vec, ctype, name, n in t.opt:
        out.append(fixed_component(is_vec, ctype, name, n))
    out.append("   end record;\n")
    out.append(f"   Option_Size : constant := {t.sizeof['mjOption']};")
    for _, _, name, _ in t.opt:
        out.append(f"   Option_Off_{ada_name(name)} : constant := {t.offset[('mjOption', name)]};")
    out.append("")
    # mjVisual: one record per sub-struct, then the aggregate
    subs = []
    for sub in ["global", "quality", "headlight", "map", "scale", "rgba"]:
        rec = f"Visual_{sub.capitalize()}"
        subs.append((sub, rec))
        out.append(f"   type {rec} is record")
        for is_vec, s, ctype, name, n in t.vis:
            if s == sub:
                out.append(fixed_component(is_vec, ctype, name, n))
        out.append("   end record;\n")
    out.append("   type Visual is record")
    for sub, rec in subs:
        out.append(f"      {sub.capitalize():<16} : {rec};")
    out.append("   end record;\n")
    out.append(f"   Visual_Size : constant := {t.sizeof['mjVisual']};")
    for _, sub, _, name, _ in t.vis:
        out.append(f"   Visual_Off_{sub.capitalize()}_{ada_name(name)} : constant := "
                   f"{t.offset[('mjVisual', f'{sub}.{name}')]};")
    out.append("")
    # mjStatistic
    out.append("   type Statistic is record")
    for is_vec, name, n in t.stat:
        out.append(fixed_component(is_vec, "mjtNum", name, n))
    out.append("   end record;\n")
    out.append(f"   Statistic_Size : constant := {t.sizeof['mjStatistic']};")
    for _, name, _ in t.stat:
        out.append(f"   Statistic_Off_{ada_name(name)} : constant := {t.offset[('mjStatistic', name)]};")
    out.append("\n   Bool_Size : constant := %d;   --  sizeof(mjtBool)\n" % t.sizeof["mjtBool"])
    out.append("end MJ.Fixed;\n")
    write(GEN / "mj-fixed.ads", "\n".join(out))


ALLOC_HELPERS = """   --  One allocating function per element kind. Each postcondition is exactly the
   --  conjunct the group layout predicate states for that array, and every group is
   --  built by a single aggregate assignment. A chain of per-component updates on a
   --  record with many access components (one call per array) makes gnatwhy3 run out
   --  of memory: 83 such calls exceeded 5 GB, the aggregate form proves in seconds.

   function New_I32 (N : Int64) return Int_Array_Access with
     Pre  => N in 0 .. Int64 (Max_Size),
     Post => I32_OK (New_I32'Result, N)
   is
   begin
      return new Int_Array'[0 .. Integer (N) - 1 => 0];
   end New_I32;

   function New_F64 (N : Int64) return Real_Array_Access with
     Pre  => N in 0 .. Int64 (Max_Size),
     Post => F64_OK (New_F64'Result, N)
   is
   begin
      return new Real_Array'[0 .. Integer (N) - 1 => 0.0];
   end New_F64;

   function New_U8 (N : Int64) return Byte_Array_Access with
     Pre  => N in 0 .. Int64 (Max_Size),
     Post => U8_OK (New_U8'Result, N)
   is
   begin
      return new Byte_Array'[0 .. Integer (N) - 1 => 0];
   end New_U8;

   function New_F32 (N : Int64) return Float32_Array_Access with
     Pre  => N in 0 .. Int64 (Max_Size),
     Post => F32_OK (New_F32'Result, N)
   is
   begin
      return new Float32_Array'[0 .. Integer (N) - 1 => 0.0];
   end New_F32;

   function New_I64 (N : Int64) return Int64_Array_Access with
     Pre  => N in 0 .. Int64 (Max_Size),
     Post => I64_OK (New_I64'Result, N)
   is
   begin
      return new Int64_Array'[0 .. Integer (N) - 1 => 0];
   end New_I64;
"""

# Fixed (non-array) components of Model, in declaration order after S.
MODEL_FIXED = [("Opt", "MJ.Fixed.Option"), ("Vis", "MJ.Fixed.Visual"), ("Stat", "MJ.Fixed.Statistic"),
               ("Flg_Gravcomp", "Boolean := False"), ("Flg_Surfacevel", "Boolean := False"),
               ("Flg_Adhesion", "Boolean := False"), ("Caps", "Capacities")]


def size_component(c: str) -> str:
    if c in SIZE_LONG:
        return f"      {ada_name(c):<16} : Int64 := 0;"
    if c in SIZE_OPT:
        return f"      {ada_name(c):<16} : Opt_Size_Type := -1;"
    return f"      {ada_name(c):<16} : Size_Type := 0;"


def emit_model(t: Tables) -> None:
    m = t.meta
    by_group = {g: [f for f in t.fields if f.group == g] for g in GROUP_ORDER}
    spec = ["with MJ.Types; use MJ.Types;", "with MJ.Fixed;", "", "package MJ.Models with SPARK_Mode is", ""]
    spec.append(f"   Size_Count     : constant := {m['nsize']};      --  int64 sizes in the .mjb size table")
    spec.append(f"   Pointer_Count  : constant := {m['nptr']};     --  arrays in MJMODEL_POINTERS")
    spec.append(f"   Version_Header : constant := {m['version']}; --  mjVERSION_HEADER")
    spec.append("")
    spec.append("   type Sizes is record")
    for c in t.sizes:
        spec.append(size_component(c))
    spec.append("   end record;\n")

    # One layout predicate per element kind: allocated, zero-based, of the given length.
    # The allocator helpers in the body establish exactly these, so every group layout
    # postcondition is a syntactic match rather than a large conjunction of attributes.
    for tag, acc in (("I32", "Int_Array_Access"), ("F64", "Real_Array_Access"), ("U8", "Byte_Array_Access"),
                     ("F32", "Float32_Array_Access"), ("I64", "Int64_Array_Access")):
        spec.append(f"   function {tag}_OK (P : {acc}; N : Int64) return Boolean is")
        spec.append(f"     (P /= null and then P'First = 0 and then Int64 (P'Length) = N);\n")

    # per-group declarations
    for g in GROUP_ORDER:
        P, T, fs = group_prefix(g), group_type(g), by_group[g]
        spec.append(f"   ---- {g} ({len(fs)} arrays)\n")
        spec.append(f"   type {T} is record")
        for f in fs:
            spec.append(f"      {f.ada:<24} : {f.acc} := null;")
        spec.append("   end record;\n")
        # One-column arrays cannot exceed Max_Size (their row count is a Size_Type),
        # so only multi-column products need a check; an empty conjunction is True.
        counts = []
        for f in fs:
            if f.nc == "1":
                continue
            e = count_long(f, m)
            if e not in counts:
                counts.append(e)
        if counts:
            spec.append(f"   function {P}_Sizes_OK (S : Sizes) return Boolean is")
            spec.append("     (" + "\n      and then ".join(f"{e} <= Int64 (Max_Size)" for e in counts) + ");\n")
        else:
            # GNAT does not warn about unreferenced formals whose name starts with "Unused".
            spec.append(f"   function {P}_Sizes_OK (Unused_S : Sizes) return Boolean is (True);\n")
        spec.append(f"   function {P}_Layout_OK (S : Sizes; G : {T}) return Boolean is")
        conj = [f"{f.reader}_OK (G.{f.ada}, {count_long(f, m)})" for f in fs]
        spec.append("     (" + "\n      and then ".join(conj) + ");\n")
        spec.append(f"   function {P}_All_Null (G : {T}) return Boolean is")
        spec.append("     (" + "\n      and then ".join(f"G.{f.ada} = null" for f in fs) + ");\n")
        spec.append(f"   procedure Allocate_{P} (S : Sizes; G : in out {T}) with")
        spec.append(f"     Pre  => {P}_Sizes_OK (S) and then {P}_All_Null (G),")
        spec.append(f"     Post => {P}_Layout_OK (S, G);")
        spec.append(f"   procedure Free_{P} (G : in out {T}) with")
        spec.append(f"     Post => {P}_All_Null (G);\n")

    spec.append("   function Sizes_In_Range (S : Sizes) return Boolean is")
    spec.append("     (" + "\n      and then ".join(f"{group_prefix(g)}_Sizes_OK (S)" for g in GROUP_ORDER) + ");\n")

    spec.append("   type Model is record")
    spec.append("      S              : Sizes;")
    for name, typ in MODEL_FIXED:
        spec.append(f"      {name:<14} : {typ};")
    for g in GROUP_ORDER:
        spec.append(f"      {GROUP_FIELD[g]:<14} : {group_type(g)};")
    spec.append("   end record;\n")

    spec.append("   function Valid_Layout (M : Model) return Boolean is")
    spec.append("     (Sizes_In_Range (M.S)\n      and then "
                + "\n      and then ".join(f"{group_prefix(g)}_Layout_OK (M.S, M.{GROUP_FIELD[g]})" for g in GROUP_ORDER) + ");\n")
    spec.append("   function All_Null (M : Model) return Boolean is")
    spec.append("     (" + "\n      and then ".join(f"{group_prefix(g)}_All_Null (M.{GROUP_FIELD[g]})" for g in GROUP_ORDER) + ");\n")

    spec.append("   --  Allocates every array zero-filled with the lengths dictated by S.")
    spec.append("   procedure Allocate (S : Sizes; M : in out Model) with")
    spec.append("     Pre  => Sizes_In_Range (S) and then All_Null (M),")
    spec.append("     Post => Valid_Layout (M) and then M.S = S;\n")
    spec.append("   procedure Free (M : in out Model) with")
    spec.append("     Post => All_Null (M);\n")
    spec.append("end MJ.Models;")
    write(GEN / "mj-models.ads", "\n".join(spec) + "\n")

    body = ["package body MJ.Models with SPARK_Mode is", "", ALLOC_HELPERS]
    for g in GROUP_ORDER:
        P, T, fs = group_prefix(g), group_type(g), by_group[g]
        body.append(f"   procedure Allocate_{P} (S : Sizes; G : in out {T}) is")
        body.append("   begin")
        body.append("      G := (" + ",\n            ".join(
            f"{f.ada:<24} => New_{f.reader} ({count_long(f, m)})" for f in fs) + ");")
        body.append(f"   end Allocate_{P};\n")
        # Deallocation has no aggregate form, so groups with more than CHUNK arrays are
        # freed in chunks: each chunk procedure states cumulatively which arrays are
        # null, which keeps every call chain short (see the comment on the allocators).
        parts = chunks(fs)
        if len(parts) > 1:
            for k in range(1, len(parts) + 1):
                done = [f for part in parts[:k] for f in part]
                body.append(f"   function {P}_Null_Upto_{k} (G : {T}) return Boolean is")
                body.append("     (" + "\n      and then ".join(f"G.{f.ada} = null" for f in done) + ");\n")
            for k, part in enumerate(parts, start=1):
                body.append(f"   procedure Free_{P}_{k} (G : in out {T}) with")
                if k > 1:
                    body.append(f"     Pre  => {P}_Null_Upto_{k - 1} (G),")
                body.append(f"     Post => {P}_Null_Upto_{k} (G)")
                body.append("   is\n   begin")
                for f in part:
                    body.append(f"      {FREE_PROC[f.acc]} (G.{f.ada});")
                body.append(f"   end Free_{P}_{k};\n")
        body.append(f"   procedure Free_{P} (G : in out {T}) is")
        body.append("   begin")
        if len(parts) > 1:
            for k in range(1, len(parts) + 1):
                body.append(f"      Free_{P}_{k} (G);")
        else:
            for f in fs:
                body.append(f"      {FREE_PROC[f.acc]} (G.{f.ada});")
        body.append(f"   end Free_{P};\n")
    # Each group is allocated into a default-null local and the model is rebuilt by one
    # aggregate, so no chain of component updates on Model reaches the prover.
    body.append("   procedure Allocate (S : Sizes; M : in out Model) is")
    for g in GROUP_ORDER:
        body.append(f"      L_{GROUP_FIELD[g]:<12} : {group_type(g)};")
    body.append("   begin")
    for g in GROUP_ORDER:
        body.append(f"      Allocate_{group_prefix(g)} (S, L_{GROUP_FIELD[g]});")
    agg = ["S              => S"] + [f"{name:<14} => M.{name}" for name, _ in MODEL_FIXED]
    agg += [f"{GROUP_FIELD[g]:<14} => L_{GROUP_FIELD[g]}" for g in GROUP_ORDER]
    body.append("      M := (" + ",\n            ".join(agg) + ");")
    body.append("   end Allocate;\n")
    body.append("   procedure Free (M : in out Model) is\n   begin")
    for g in GROUP_ORDER:
        body.append(f"      Free_{group_prefix(g)} (M.{GROUP_FIELD[g]});")
    body.append("   end Free;\n")
    body.append("end MJ.Models;")
    write(GEN / "mj-models.adb", "\n".join(body) + "\n")


# ----------------------------------------------------------------------------- readers

READ_CALL = {   # reader tag -> (getter, bytes)
    "I32": ("Get_I32", 4), "I64": ("Get_I64", 8), "U8": ("Get_U8", 1),
}


def emit_element_loop(out, indent, arr, f, field_lit, layout_pred):
    """Emit the call filling access array `arr` (e.g. 'G.Body_Pos') for field f.

    The element loops live in the small helper procedures Read_*_Array below,
    so a group reader is a flat sequence of calls: no loop invariant has to
    restate the group layout at every array, which kept gnatwhy3 and the
    optimiser from blowing up on the 83-array flex group.
    """
    sp = " " * indent
    if f.reader in ("F64", "F32"):
        out.append(f"{sp}Read_{f.reader}_Array (B, Pos, {arr}.all, Bad);")
        out.append(f"{sp}if Bad >= 0 then")
        out.append(f"{sp}   Result := (Non_Finite_Value, {field_lit}, Bad);")
        out.append(f"{sp}   return;")
        out.append(f"{sp}end if;")
    else:
        out.append(f"{sp}Read_{f.reader}_Array (B, Pos, {arr}.all);")


HELPERS = """
   --  One element loop per element kind. B'First = 0 and A'First = 0 always;
   --  the caller has checked that the bytes for the whole array are present.

   procedure Read_I32_Array (B : Byte_Array; Pos : Natural; A : in out Int_Array) with
     Pre => B'First = 0 and then Int64 (B'Length) <= Int64 (Natural'Last) and then A'First = 0 and then Pos <= B'Length
            and then Int64 (B'Length) - Int64 (Pos) >= 4 * Int64 (A'Length)
   is
   begin
      for I in A'Range loop
         A (I) := Get_I32 (B, Pos + 4 * I);
      end loop;
   end Read_I32_Array;

   procedure Read_I64_Array (B : Byte_Array; Pos : Natural; A : in out Int64_Array) with
     Pre => B'First = 0 and then Int64 (B'Length) <= Int64 (Natural'Last) and then A'First = 0 and then Pos <= B'Length
            and then Int64 (B'Length) - Int64 (Pos) >= 8 * Int64 (A'Length)
   is
   begin
      for I in A'Range loop
         A (I) := Get_I64 (B, Pos + 8 * I);
      end loop;
   end Read_I64_Array;

   procedure Read_U8_Array (B : Byte_Array; Pos : Natural; A : in out Byte_Array) with
     Pre => B'First = 0 and then Int64 (B'Length) <= Int64 (Natural'Last) and then A'First = 0 and then Pos <= B'Length
            and then Int64 (B'Length) - Int64 (Pos) >= Int64 (A'Length)
   is
   begin
      for I in A'Range loop
         A (I) := Get_U8 (B, Pos + I);
      end loop;
   end Read_U8_Array;

   --  Bad is -1 when every value is finite, else the index of the first that is not.
   procedure Read_F64_Array (B : Byte_Array; Pos : Natural; A : in out Real_Array; Bad : out Integer) with
     Pre  => B'First = 0 and then Int64 (B'Length) <= Int64 (Natural'Last) and then A'First = 0 and then Pos <= B'Length
             and then Int64 (B'Length) - Int64 (Pos) >= 8 * Int64 (A'Length),
     Post => Bad = -1 or else Bad in A'Range
   is
      U : Unsigned_64;
   begin
      Bad := -1;
      for I in A'Range loop
         U := Get_U64 (B, Pos + 8 * I);
         if not Is_Finite_F64 (U) then
            Bad := I;
            return;
         end if;
         A (I) := Bits_To_Real (U);
      end loop;
   end Read_F64_Array;

   procedure Read_F32_Array (B : Byte_Array; Pos : Natural; A : in out Float32_Array; Bad : out Integer) with
     Pre  => B'First = 0 and then Int64 (B'Length) <= Int64 (Natural'Last) and then A'First = 0 and then Pos <= B'Length
             and then Int64 (B'Length) - Int64 (Pos) >= 4 * Int64 (A'Length),
     Post => Bad = -1 or else Bad in A'Range
   is
      U : Unsigned_32;
   begin
      Bad := -1;
      for I in A'Range loop
         U := Get_U32 (B, Pos + 4 * I);
         if not Is_Finite_F32 (U) then
            Bad := I;
            return;
         end if;
         A (I) := Bits_To_Float (U);
      end loop;
   end Read_F32_Array;
"""


def fixed_members(t: Tables):
    """Yield (struct, ada_path, ctype, is_vec, n, offset_const, ordinal, block) for every fixed member."""
    for i, (is_vec, ctype, name, n) in enumerate(t.opt):
        yield ("Opt", f"Opt.{ada_name(name)}", ctype, is_vec, n, f"Option_Off_{ada_name(name)}", i, "Option_Block")
    for i, (is_vec, sub, ctype, name, n) in enumerate(t.vis):
        yield ("Vis", f"Vis.{sub.capitalize()}.{ada_name(name)}", ctype, is_vec, n,
               f"Visual_Off_{sub.capitalize()}_{ada_name(name)}", i, "Visual_Block")
    for i, (is_vec, name, n) in enumerate(t.stat):
        yield ("Stat", f"Stat.{ada_name(name)}", "mjtNum", is_vec, n, f"Statistic_Off_{ada_name(name)}", i, "Statistic_Block")


def emit_fixed_member_read(out, path, ctype, is_vec, n, off, ordinal, block):
    """Read one mjOption/mjVisual/mjStatistic member from B at Base + off."""
    def one(target, byte_off):
        if ctype == "mjtNum":
            out.append(f"      U64 := Get_U64 (B, Base + {byte_off});")
            out.append(f"      if not Is_Finite_F64 (U64) then Result := (Non_Finite_Value, {block}, {ordinal}); return; end if;")
            out.append(f"      {target} := Bits_To_Real (U64);")
        elif ctype == "float":
            out.append(f"      U32 := Get_U32 (B, Base + {byte_off});")
            out.append(f"      if not Is_Finite_F32 (U32) then Result := (Non_Finite_Value, {block}, {ordinal}); return; end if;")
            out.append(f"      {target} := Bits_To_Float (U32);")
        else:
            out.append(f"      {target} := Get_I32 (B, Base + {byte_off});")
    size = {"mjtNum": 8, "float": 4, "int": 4}[ctype]
    if is_vec:
        for k in range(n):
            one(f"{path} ({k})", f"{off} + {k * size}")
    else:
        one(path, off)


def file_group_order(t: Tables) -> list:
    """Groups sorted by the position of their first array in the .mjb file.

    The readers fill one group at a time, so every group's arrays must be
    contiguous in MJMODEL_POINTERS; the assertion guards that assumption.
    """
    first = {}
    for i, f in enumerate(t.fields):
        first.setdefault(f.group, i)
    order = sorted(GROUP_ORDER, key=lambda g: first[g])
    pos = 0
    for g in order:
        n = sum(1 for f in t.fields if f.group == g)
        block = t.fields[pos:pos + n]
        if any(f.group != g for f in block):
            sys.exit(f"arrays of group {g} are not contiguous in MJMODEL_POINTERS; the per-group readers cannot be used")
        pos += n
    return order


def emit_readers(t: Tables) -> None:
    m = t.meta
    by_group = {g: [f for f in t.fields if f.group == g] for g in GROUP_ORDER}
    # MJ.Types, MJ.Fields, MJ.Models are already use-visible through the parent MJ.MJB.
    spec = ["with MJ.Fixed;  use MJ.Fixed;", "",
            "package MJ.MJB.Readers with SPARK_Mode is", "",
            "   Fixed_Bytes : constant := Option_Size + Visual_Size + Statistic_Size + 2 * Bool_Size;", "",
            "   procedure Read_Sizes (B : Byte_Array; Pos : in out Natural; S : out Sizes; Result : out Load_Result) with",
            "     Pre  => B'First = 0 and then Int64 (B'Length) <= Int64 (Natural'Last) and then Pos <= B'Length",
            "             and then Int64 (B'Length) - Int64 (Pos) >= 8 * Size_Count,",
            "     Post => Pos <= B'Length and then (if Result.Status = OK then Pos = Pos'Old + 8 * Size_Count);", "",
            "   procedure Read_Fixed (B : Byte_Array; Pos : in out Natural; Opt : out Option; Vis : out Visual;",
            "                         Stat : out Statistic; Gravcomp, Surfacevel : out Boolean; Result : out Load_Result) with",
            "     Pre  => B'First = 0 and then Int64 (B'Length) <= Int64 (Natural'Last) and then Pos <= B'Length",
            "             and then Int64 (B'Length) - Int64 (Pos) >= Fixed_Bytes,",
            "     Post => Pos <= B'Length and then (if Result.Status = OK then Pos = Pos'Old + Fixed_Bytes);", ""]
    for g in GROUP_ORDER:
        P, T = group_prefix(g), group_type(g)
        spec.append(f"   procedure Read_{P} (B : Byte_Array; Pos : in out Natural; S : Sizes; G : in out {T}; Result : out Load_Result) with")
        spec.append(f"     Pre  => B'First = 0 and then Int64 (B'Length) <= Int64 (Natural'Last) and then Pos <= B'Length and then {P}_Layout_OK (S, G),")
        spec.append(f"     Post => Pos <= B'Length and then {P}_Layout_OK (S, G);")
        spec.append("")
    spec.append("   --  Allocates every array of M.S and fills it from B; M keeps its other components.")
    spec.append("   --  The arrays are allocated whatever the outcome (partly filled after a failure),")
    spec.append("   --  so the caller frees M when Result is not OK.")
    spec.append("   procedure Read_Arrays (B : Byte_Array; Pos : in out Natural; M : in out Model; Result : out Load_Result) with")
    spec.append("     Pre  => B'First = 0 and then Int64 (B'Length) <= Int64 (Natural'Last) and then Pos <= B'Length and then Sizes_In_Range (M.S) and then All_Null (M),")
    spec.append("     Post => Pos <= B'Length and then M.S = M.S'Old and then Valid_Layout (M);")
    spec.append("")
    spec.append("end MJ.MJB.Readers;")
    write(GEN / "mj-mjb-readers.ads", "\n".join(spec) + "\n")

    body = [POLICY_PRAGMA, "with Interfaces; use Interfaces;", "with MJ.Bytes;   use MJ.Bytes;", "",
            "package body MJ.MJB.Readers with SPARK_Mode is", HELPERS]
    # Read_Sizes: the size table is read in chunks of CHUNK fields, so that no long chain
    # of updates to S (98 components, one range check and early return each) reaches the
    # prover; the unchunked form made gnatwhy3 exceed 5 GB.
    size_parts = chunks(list(enumerate(t.sizes)))
    for k, part in enumerate(size_parts, start=1):
        body.append(f"   procedure Read_Sizes_{k} (B : Byte_Array; P : Natural; S : in out Sizes; Result : out Load_Result) with")
        body.append("     Pre => B'First = 0 and then Int64 (B'Length) <= Int64 (Natural'Last) and then P <= B'Length and then Int64 (B'Length) - Int64 (P) >= 8 * Size_Count")
        body.append("   is")
        body.append("      V : Int64;")
        body.append("   begin")
        body.append("      Result := OK_Result;")
        for i, c in part:
            a = ada_name(c)
            body.append(f"      V := Get_I64 (B, P + {8 * i});")
            if c in SIZE_LONG:
                body.append(f"      S.{a} := V;")
            else:
                lo = "-1" if c in SIZE_OPT else "0"
                body.append(f"      if V not in {lo} .. Int64 (Max_Size) then")
                body.append(f"         Result := (Size_Out_Of_Range, Size_Table, {i});")
                body.append("         return;")
                body.append("      end if;")
                body.append(f"      S.{a} := Integer (V);")
        body.append(f"   end Read_Sizes_{k};\n")
    body.append("   procedure Read_Sizes (B : Byte_Array; Pos : in out Natural; S : out Sizes; Result : out Load_Result) is")
    body.append("      P : constant Natural := Pos;")
    body.append("   begin")
    body.append("      S := (others => <>);")
    for k in range(1, len(size_parts) + 1):
        if k > 1:
            body.append("      if Result.Status /= OK then return; end if;")
        body.append(f"      Read_Sizes_{k} (B, P, S, Result);")
    body.append("      if Result.Status /= OK then return; end if;")
    body.append("      Pos := P + 8 * Size_Count;")
    body.append("   end Read_Sizes;\n")

    # Read_Fixed: the members of mjOption, mjVisual and mjStatistic are read by chunk
    # procedures of at most CHUNK scalar writes each, for the same reason.
    def fixed_chunks(members: list) -> list:
        parts, cur, cnt = [], [], 0
        for mem in members:
            width = mem[4] if mem[3] else 1
            if cur and cnt + width > CHUNK:
                parts.append(cur)
                cur, cnt = [], 0
            cur.append(mem)
            cnt += width
        if cur:
            parts.append(cur)
        return parts

    struct_info = {"Opt": ("Option", "Option_Size"), "Vis": ("Visual", "Visual_Size"), "Stat": ("Statistic", "Statistic_Size")}
    by_struct = {s: [] for s in struct_info}
    for mem in fixed_members(t):
        by_struct[mem[0]].append(mem)
    driver_calls = {}
    for struct, (typ, size_const) in struct_info.items():
        driver_calls[struct] = []
        for k, part in enumerate(fixed_chunks(by_struct[struct]), start=1):
            name = f"Read_{typ}_{k}"
            driver_calls[struct].append(name)
            body.append(f"   procedure {name} (B : Byte_Array; Base : Natural; {struct} : in out {typ}; Result : out Load_Result) with")
            body.append(f"     Pre => B'First = 0 and then Int64 (B'Length) <= Int64 (Natural'Last) and then Base <= B'Length and then Int64 (B'Length) - Int64 (Base) >= {size_const}")
            body.append("   is")
            ctypes = {mem[2] for mem in part}
            if "mjtNum" in ctypes:
                body.append("      U64 : Unsigned_64;")
            if "float" in ctypes:
                body.append("      U32 : Unsigned_32;")
            body.append("   begin")
            body.append("      Result := OK_Result;")
            for _, path, ctype, is_vec, n, off, ordinal, block in part:
                emit_fixed_member_read(body, path, ctype, is_vec, n, off, ordinal, block)
            body.append(f"   end {name};\n")
    body.append("   procedure Read_Fixed (B : Byte_Array; Pos : in out Natural; Opt : out Option; Vis : out Visual;")
    body.append("                         Stat : out Statistic; Gravcomp, Surfacevel : out Boolean; Result : out Load_Result) is")
    body.append("      Base : Natural := Pos;")
    body.append("   begin")
    body.append("      Opt := (others => <>);")
    body.append("      Vis := (others => <>);")
    body.append("      Stat := (others => <>);")
    body.append("      Gravcomp := False;")
    body.append("      Surfacevel := False;")
    for struct, (typ, size_const) in struct_info.items():
        body.append(f"      --  {typ}")
        for name in driver_calls[struct]:
            body.append(f"      {name} (B, Base, {struct}, Result);")
            body.append("      if Result.Status /= OK then return; end if;")
        body.append(f"      Base := Base + {size_const};")
    body.append("      Gravcomp := Get_U8 (B, Base) /= 0;")
    body.append("      Surfacevel := Get_U8 (B, Base + Bool_Size) /= 0;")
    body.append("      Pos := Base + 2 * Bool_Size;")
    body.append("   end Read_Fixed;\n")
    # one reader per group; groups with more than CHUNK arrays are read by a sequence
    # of chunk procedures so that no long chain of updates to G reaches the prover
    def emit_array_reads(name: str, part: list) -> None:
        body.append(f"   procedure {name} (B : Byte_Array; Pos : in out Natural; S : Sizes; G : in out {T}; Result : out Load_Result)")
        if name != f"Read_{P}":
            body.append("   with")
            body.append(f"     Pre  => B'First = 0 and then Int64 (B'Length) <= Int64 (Natural'Last) and then Pos <= B'Length and then {P}_Layout_OK (S, G),")
            body.append(f"     Post => Pos <= B'Length and then {P}_Layout_OK (S, G)")
        body.append("   is")
        body.append("      Count  : Int64;")
        body.append("      Nbytes : Int64;")
        if any(f.reader in ("F64", "F32") for f in part):
            body.append("      Bad    : Integer;")
        body.append("   begin")
        body.append("      Result := OK_Result;")
        for f in part:
            body.append(f"      --  {f.name} : {f.ctype} ({f.nr} x {f.nc})")
            body.append(f"      Count  := {count_long(f, m)};")
            body.append(f"      Nbytes := Count * {f.nbytes};")
            body.append("      if Int64 (B'Length) - Int64 (Pos) < Nbytes then")
            body.append(f"         Result := (Truncated, {f.ada}, -1);")
            body.append("         return;")
            body.append("      end if;")
            emit_element_loop(body, 6, f"G.{f.ada}", f, f.ada, f"{P}_Layout_OK (S, G)")
            body.append("      Pos := Pos + Integer (Nbytes);")
        body.append(f"   end {name};\n")

    for g in GROUP_ORDER:
        P, T, fs = group_prefix(g), group_type(g), by_group[g]
        parts = chunks(fs)
        if len(parts) == 1:
            emit_array_reads(f"Read_{P}", fs)
            continue
        for k, part in enumerate(parts, start=1):
            emit_array_reads(f"Read_{P}_{k}", part)
        body.append(f"   procedure Read_{P} (B : Byte_Array; Pos : in out Natural; S : Sizes; G : in out {T}; Result : out Load_Result) is")
        body.append("   begin")
        for k in range(1, len(parts) + 1):
            if k > 1:
                body.append("      if Result.Status /= OK then return; end if;")
            body.append(f"      Read_{P}_{k} (B, Pos, S, G, Result);")
        body.append(f"   end Read_{P};\n")
    # Allocate and read each group through one helper. This halves the driver's
    # call chain and keeps the per-group branch out of the whole-model context.
    # Every group is allocated even after a read failure, so the final Model has
    # a valid layout and the caller can free it through the normal error path.
    for g in file_group_order(t):
        P, T = group_prefix(g), group_type(g)
        body.append(f"   procedure Allocate_Read_{P}")
        body.append("     (B : Byte_Array; Pos : in out Natural; S : Sizes;")
        body.append(f"      G : in out {T}; Result : in out Load_Result) with")
        body.append("     Pre => B'First = 0 and then Int64 (B'Length) <= Int64 (Natural'Last)")
        body.append(f"       and then Pos <= B'Length and then {P}_Sizes_OK (S)")
        body.append(f"       and then {P}_All_Null (G),")
        body.append(f"     Post => Pos <= B'Length and then {P}_Layout_OK (S, G)")
        body.append("       and then (if Result'Old.Status /= OK then Result = Result'Old and Pos = Pos'Old);\n")
        body.append(f"   procedure Allocate_Read_{P}")
        body.append("     (B : Byte_Array; Pos : in out Natural; S : Sizes;")
        body.append(f"      G : in out {T}; Result : in out Load_Result) is")
        body.append("   begin")
        body.append(f"      Allocate_{P} (S, G);")
        body.append("      if Result.Status = OK then")
        body.append(f"         Read_{P} (B, Pos, S, G, Result);")
        body.append("      end if;")
        body.append(f"   end Allocate_Read_{P};\n")
    body.append("   procedure Read_Arrays (B : Byte_Array; Pos : in out Natural; M : in out Model; Result : out Load_Result) is")
    for g in GROUP_ORDER:
        body.append(f"      L_{GROUP_FIELD[g]:<12} : {group_type(g)};")
    body.append("   begin")
    body.append("      Result := (OK, None, -1);")
    for g in file_group_order(t):
        body.append(f"      Allocate_Read_{group_prefix(g)} (B, Pos, M.S, L_{GROUP_FIELD[g]}, Result);")
    agg = ["S              => M.S"] + [f"{name:<14} => M.{name}" for name, _ in MODEL_FIXED]
    agg += [f"{GROUP_FIELD[g]:<14} => L_{GROUP_FIELD[g]}" for g in GROUP_ORDER]
    body.append("      M := (" + ",\n            ".join(agg) + ");")
    body.append("   end Read_Arrays;\n")
    body.append("end MJ.MJB.Readers;")
    write(GEN / "mj-mjb-readers.adb", "\n".join(body) + "\n")


# ----------------------------------------------------------------------------- serializer (test support)


def emit_serialize(t: Tables) -> None:
    m = t.meta
    spec = """with MJ.Types; use MJ.Types;
with MJ.Models; use MJ.Models;

--  Inverse of the .mjb reader, used by the tests for round trips and for
--  building corrupted images. Plain Ada, not SPARK.
package MJB_Serialize is
   function Serialized_Size (M : Model) return Int64;
   --  Requires B'First = 0 and B'Length = Serialized_Size (M).
   procedure Serialize (M : Model; B : out Byte_Array);
end MJB_Serialize;
"""
    write(TGEN / "mjb_serialize.ads", spec)
    out = ["with Interfaces; use Interfaces;", "with Ada.Unchecked_Conversion;", "with MJ.Fixed; use MJ.Fixed;", "",
           "package body MJB_Serialize is", "",
           "   function Real_Bits  is new Ada.Unchecked_Conversion (Real, Unsigned_64);",
           "   function Float_Bits is new Ada.Unchecked_Conversion (Float, Unsigned_32);", "",
           "   procedure Put_U8 (B : in out Byte_Array; Pos : Natural; V : Unsigned_8) is",
           "   begin", "      B (Pos) := V;", "   end Put_U8;", "",
           "   procedure Put_U32 (B : in out Byte_Array; Pos : Natural; V : Unsigned_32) is",
           "   begin",
           "      for K in 0 .. 3 loop",
           "         B (Pos + K) := Unsigned_8 (Shift_Right (V, 8 * K) and 16#FF#);",
           "      end loop;", "   end Put_U32;", "",
           "   procedure Put_U64 (B : in out Byte_Array; Pos : Natural; V : Unsigned_64) is",
           "   begin",
           "      for K in 0 .. 7 loop",
           "         B (Pos + K) := Unsigned_8 (Shift_Right (V, 8 * K) and 16#FF#);",
           "      end loop;", "   end Put_U64;", "",
           "   procedure Put_I32 (B : in out Byte_Array; Pos : Natural; V : Integer) is",
           "   begin",
           "      Put_U32 (B, Pos, (if V < 0 then Unsigned_32 (Int64 (V) + 2**32) else Unsigned_32 (V)));",
           "   end Put_I32;", "",
           "   procedure Put_I64 (B : in out Byte_Array; Pos : Natural; V : Int64) is",
           "   begin",
           "      Put_U64 (B, Pos, (if V < 0 then Unsigned_64 (V + 2**62 + 2**62) + 2**63 else Unsigned_64 (V)));",
           "   end Put_I64;", "",
           "   function Serialized_Size (M : Model) return Int64 is",
           "      S : Sizes renames M.S;",
           "      N : Int64 := 20 + 8 * Size_Count + Option_Size + Visual_Size + Statistic_Size + 2 * Bool_Size;",
           "   begin"]
    for f in t.fields:
        out.append(f"      N := N + ({count_long(f, m)}) * {f.nbytes};")
    out.append("      return N;")
    out.append("   end Serialized_Size;\n")
    out.append("   procedure Serialize (M : Model; B : out Byte_Array) is")
    out.append("      S     : Sizes renames M.S;")
    out.append("      Pos   : Natural := 0;")
    out.append("      Base  : Natural := 0;")
    out.append("      Count : Int64;")
    out.append("   begin")
    out.append("      B := [others => 0];")
    out.append("      Put_I32 (B, 0, 54321);")
    out.append("      Put_I32 (B, 4, 8);")
    out.append("      Put_I32 (B, 8, Size_Count);")
    out.append("      Put_I32 (B, 12, Version_Header);")
    out.append("      Put_I32 (B, 16, Pointer_Count);")
    out.append("      Pos := 20;")
    for i, c in enumerate(t.sizes):
        conv = "" if c in SIZE_LONG else "Int64 "
        out.append(f"      Put_I64 (B, Pos + {8 * i}, {conv}(S.{ada_name(c)}));")
    out.append("      Pos := Pos + 8 * Size_Count;")
    current = None
    for struct, path, ctype, is_vec, n, off, ordinal, block in fixed_members(t):
        if struct != current:
            if current is not None:
                out.append(f"      Pos := Pos + {'Option_Size' if current == 'Opt' else 'Visual_Size'};")
            current = struct
            out.append("      Base := Pos;")
        size = {"mjtNum": 8, "float": 4, "int": 4}[ctype]
        for k in range(n if is_vec else 1):
            target = f"M.{path} ({k})" if is_vec else f"M.{path}"
            at = f"Base + {off} + {k * size}"
            if ctype == "mjtNum":
                out.append(f"      Put_U64 (B, {at}, Real_Bits ({target}));")
            elif ctype == "float":
                out.append(f"      Put_U32 (B, {at}, Float_Bits ({target}));")
            else:
                out.append(f"      Put_I32 (B, {at}, {target});")
    out.append("      Pos := Pos + Statistic_Size;")
    out.append("      Put_U8 (B, Pos, (if M.Flg_Gravcomp then 1 else 0));")
    out.append("      Put_U8 (B, Pos + Bool_Size, (if M.Flg_Surfacevel then 1 else 0));")
    out.append("      Pos := Pos + 2 * Bool_Size;")
    for f in t.fields:
        arr = f"M.{GROUP_FIELD[f.group]}.{f.ada}"
        out.append(f"      Count := {count_long(f, m)};")
        out.append("      for I in 0 .. Integer (Count) - 1 loop")
        if f.reader == "F64":
            out.append(f"         Put_U64 (B, Pos + 8 * I, Real_Bits ({arr} (I)));")
        elif f.reader == "F32":
            out.append(f"         Put_U32 (B, Pos + 4 * I, Float_Bits ({arr} (I)));")
        elif f.reader == "I64":
            out.append(f"         Put_I64 (B, Pos + 8 * I, {arr} (I));")
        elif f.reader == "I32":
            out.append(f"         Put_I32 (B, Pos + 4 * I, {arr} (I));")
        else:
            out.append(f"         Put_U8 (B, Pos + I, {arr} (I));")
        out.append("      end loop;")
        out.append(f"      Pos := Pos + Integer (Count) * {f.nbytes};")
    out.append("   end Serialize;\n")
    out.append("end MJB_Serialize;")
    write(TGEN / "mjb_serialize.adb", "\n".join(out) + "\n")


# ----------------------------------------------------------------------------- generated clauses

ENGINE_IO = ROOT / "mujoco" / "src" / "engine" / "engine_io.c"
REFS = ROOT / "tools" / "refs.txt"

# id arrays that may legitimately hold -1 (spec 5.2); every other reference is >= 0
ALLOW_MINUS_ONE = {
    "body_mocapid", "body_plugin", "geom_matid", "geom_dataid", "site_matid", "skin_matid",
    "tendon_matid", "cam_targetbodyid", "light_targetbodyid", "jnt_actuatorid", "mesh_graphadr",
    "mesh_texcoordadr", "flex_texcoordadr", "skin_texcoordadr", "actuator_plugin", "sensor_plugin",
    "hfield_pathadr", "mesh_pathadr", "skin_pathadr", "tex_pathadr", "tendon_treeid", "dof_parentid",
}


def extract_refs() -> list:
    """Rows (adr, ntarget, num) of the MJMODEL_REFERENCES table in engine_io.c."""
    text = ENGINE_IO.read_text()
    start = text.index("#define MJMODEL_REFERENCES")
    end = text.index("#define X(adrarray", start)
    rows = []
    for m in re.finditer(r"X\(\s*(\w+)\s*,\s*([\w*]+)\s*,\s*(\w+)\s*,\s*(?:m->)?(\w+)\s*\)", text[start:end]):
        adr, _nadrs, target, num = m.groups()
        rows.append((adr, target, None if num == "0" else num))
    if len(rows) < 90:
        sys.exit(f"reference table extraction found only {len(rows)} rows")
    REFS.write_text("".join(f"{a} {t} {n or '-'}\n" for a, t, n in rows), newline="\n")
    return rows


def field_path(t: Tables, cname: str) -> str:
    f = next(f for f in t.fields if f.name == cname)
    return f"M.{GROUP_FIELD[f.group]}.{f.ada}"


# Bounding boxes hold mjMAXVAL-sized half-extents for planes (found on model/replicate/*):
# bounds, not physical parameters, so they are checked against tier 1 instead of tier 0.
TIER1_FIELDS = {"bvh_aabb", "geom_aabb", "oct_aabb"}


def real_tier(f: Field) -> str:
    return "Tier1_Real" if f.name in TIER1_FIELDS else "Tier0_Real"


POLICY_PRAGMA = (
    "--  Contracts and loop invariants in this unit are proven by GNATprove and are\n"
    "--  not evaluated at run time: evaluating them made the GCC optimiser inline\n"
    "--  whole-model invariants at every call site (gnat1 reached 65 GB on 2026-09-03).\n"
    "pragma Assertion_Policy (Pre => Ignore, Post => Ignore, Loop_Invariant => Ignore,\n"
    "                         Loop_Variant => Ignore, Assert => Check);\n")


def emit_gen_clauses(t: Tables, refs: list) -> None:
    out = [POLICY_PRAGMA, "with Interfaces; use type Interfaces.Unsigned_8;", "",
           "package MJ.Models.Gen_Clauses with SPARK_Mode is", "",
           "   --  Spec 5.2: every reference of the C MJMODEL_REFERENCES table is in range.",
           "   --  Pairs (adr, num): num in 0 .. target, adr = -1 allowed only when num = 0.",
           "   --  Plain ids: in -1 .. target - 1 when -1 is meaningful for that field, else 0 .. target - 1.",
           "   --  Element preconditions are deliberately O(1): only the non-null and range",
           "   --  facts the body needs, never a whole-model invariant.", ""]
    for adr, target, num in refs:
        a = field_path(t, adr)
        tgt = f"M.S.{ada_name(target)}"
        if num:
            n = field_path(t, num)
            body = (f"{n} (I) in 0 .. {tgt}\n"
                    f"      and then (if {n} (I) = 0 then {a} (I) in -1 .. {tgt}\n"
                    f"                else {a} (I) in 0 .. {tgt} - {n} (I))")
            pre = (f"{a} /= null and then {n} /= null and then {n}'First = {a}'First\n"
                   f"               and then {n}'Length = {a}'Length and then I in {a}'Range")
        else:
            lo = "-1" if adr in ALLOW_MINUS_ONE else "0"
            body = f"{a} (I) in {lo} .. {tgt} - 1"
            pre = f"{a} /= null and then I in {a}'Range"
        out.append(f"   function Ref_{ada_name(adr)}_At (M : Model; I : Integer) return Boolean is")
        out.append(f"     ({body})")
        out.append(f"   with Pre => {pre};\n")
    out.append("   function Refs_OK (M : Model) return Boolean is")
    # Each operand is safe under Valid_Layout alone. A Boolean conjunction
    # avoids importing all earlier quantified results into every later check.
    out.append("     (" + "\n      and ".join(
        f"(for all I in {field_path(t, adr)}'Range => Ref_{ada_name(adr)}_At (M, I))" for adr, _, _ in refs) + ")")
    out.append("   with Pre => Valid_Layout (M);")
    out.append("   --  Composition uses each element contract; its Boolean body is proved separately.")
    for adr, _, _ in refs:
        out.append(f'   pragma Annotate (GNATprove, Hide_Info, "Expression_Function_Body", Ref_{ada_name(adr)}_At);')
    out.append("   pragma No_Inline (Refs_OK);\n")
    reals = [f for f in t.fields if f.ctype == "mjtNum"]
    for tier in (0, 1):
        out += [f"   function Real_Values_In_Tier{tier} (Values : Real_Array) return Boolean is",
                f"     (for all Value of Values => Value in Tier{tier}_Real)",
                "   with Global => null;", ""]
    out.append("   --  Spec 5.10: every mjtNum array value has magnitude at most Max_Val (tier 0),")
    out.append("   --  except the bounding boxes, whose half-extents for planes are mjMAXVAL-sized")
    out.append("   --  bounds rather than physical quantities: those are tier 1.")
    out.append("   function Reals_In_Tier0 (M : Model) return Boolean is")
    out.append("     (" + "\n      and ".join(
        f"Real_Values_In_Tier{1 if f.name in TIER1_FIELDS else 0} (M.{GROUP_FIELD[f.group]}.{f.ada}.all)"
        for f in reals) + ")")
    out.append("   with Pre => Valid_Layout (M);")
    for tier in (0, 1):
        out.append(f'   pragma Annotate (GNATprove, Hide_Info, "Expression_Function_Body", Real_Values_In_Tier{tier});')
    out.append("   pragma No_Inline (Reals_In_Tier0);\n")
    bools = [f for f in t.fields if f.ctype == "mjtBool"]
    out += ["   function Boolean_Values_OK (Values : Byte_Array) return Boolean is",
            "     (for all Value of Values => Value <= 1)",
            "   with Global => null;", ""]
    out.append("   --  Spec 5.3: every mjtBool array holds only 0 or 1.")
    out.append("   function Bools_OK (M : Model) return Boolean is")
    out.append("     (" + "\n      and ".join(
        f"Boolean_Values_OK (M.{GROUP_FIELD[f.group]}.{f.ada}.all)" for f in bools) + ")")
    out.append("   with Pre => Valid_Layout (M);")
    out.append('   pragma Annotate (GNATprove, Hide_Info, "Expression_Function_Body", Boolean_Values_OK);')
    out.append("   pragma No_Inline (Bools_OK);\n")
    out.append("end MJ.Models.Gen_Clauses;")
    write(GEN / "mj-models-gen_clauses.ads", "\n".join(out) + "\n")


def emit_diagnose(t: Tables, refs: list) -> None:
    def emit(name, predicate, status, rows):
        # Bound each diagnostic body: a long chain of whole-Model scans causes
        # GNATprove to build huge contexts even though the model is read-only.
        out = [POLICY_PRAGMA, "separate (MJ.Validation)",
               f"procedure {name} (M : Model; Result : out Load_Result) is",
               f'   pragma Annotate (GNATprove, Hide_Info, "Expression_Function_Body", {predicate});']
        scans = []
        for number, first in enumerate(range(0, len(rows), CHUNK), 1):
            scan = f"Scan_{name.removeprefix('Diagnose_')}_{number}"
            scans.append(scan)
            chunk = rows[first:first + CHUNK]
            requirements = list(dict.fromkeys(
                requirement.replace("M.", "Input.")
                for _, _, _, required in chunk for requirement in required))
            out += [f"   procedure {scan} (Input : Model; Diagnostic : out Load_Result) with",
                    "     Pre => " + "\n       and then ".join(requirements) + ";",
                    f"   procedure {scan} (Input : Model; Diagnostic : out Load_Result) is",
                    "   begin", "      Diagnostic := OK_Result;"]
            for array, test, field, _ in chunk:
                array, test = array.replace("M.", "Input."), test.replace("M.", "Input.").replace("(M,", "(Input,")
                out += [f"      for I in {array}'Range loop",
                        f"         if not ({test}) then",
                        f"            Diagnostic := ({status}, {field}, I);",
                        "            return;", "         end if;", "      end loop;"]
            out += [f"   end {scan};", ""]
        out += ["begin", f"   if {predicate} (M) then",
                "      Result := OK_Result;", "      return;", "   end if;",
                "   --  The predicate established failure; the scans locate its first field."]
        for scan in scans:
            out += [f"   {scan} (M, Result);", "   if Result.Status /= OK then",
                    "      return;", "   end if;"]
        out += [f"   Result := ({status}, Header, -1);", f"end {name};"]
        filename = "mj-validation-" + name.lower() + ".adb"
        write(GEN / filename, "\n".join(out) + "\n")

    reference_rows = []
    for adr, _, num in refs:
        array = field_path(t, adr)
        required = [f"{array} /= null"]
        if num:
            counts = field_path(t, num)
            required += [f"{counts} /= null", f"{counts}'First = {array}'First",
                         f"{counts}'Length = {array}'Length"]
        reference_rows.append((array, f"Ref_{ada_name(adr)}_At (M, I)", ada_name(adr), required))
    emit("Diagnose_Refs", "Refs_OK", "Invalid_Reference", reference_rows)
    emit("Diagnose_Reals", "Reals_In_Tier0", "Invalid_Parameter", [
        (f"M.{GROUP_FIELD[f.group]}.{f.ada}",
         f"M.{GROUP_FIELD[f.group]}.{f.ada} (I) in {real_tier(f)}", f.ada,
         [f"M.{GROUP_FIELD[f.group]}.{f.ada} /= null"])
        for f in t.fields if f.ctype == "mjtNum"])
    emit("Diagnose_Bools", "Bools_OK", "Invalid_Parameter", [
        (f"M.{GROUP_FIELD[f.group]}.{f.ada}", f"M.{GROUP_FIELD[f.group]}.{f.ada} (I) <= 1", f.ada,
         [f"M.{GROUP_FIELD[f.group]}.{f.ada} /= null"])
        for f in t.fields if f.ctype == "mjtBool"])


# ----------------------------------------------------------------------------- main


def main() -> None:
    t = load_tables()
    refs = extract_refs()
    emit_fields(t)
    emit_fixed(t)
    emit_model(t)
    emit_readers(t)
    emit_serialize(t)
    emit_gen_clauses(t, refs)
    emit_diagnose(t, refs)
    print(f"generated {len(t.fields)} fields in {len(GROUP_ORDER)} groups, {len(refs)} reference rows")


if __name__ == "__main__":
    main()
